In [16]:
import os
import pandas as pd

In [17]:
directory_path = r'<csv_directory>'
csv_name = r'<csv_name>'
target_path = r'<path_to_new_csv>'
desired_order = ['city', 'link', 'name', 'rating', 'price_lower', 'price_higher', 'price_type','longitude', 'latitude', 'cuisine', 'meal_type','purpose']

In [18]:
def extract_prices(price_range_str):
    try:
        price_lower = int(price_range_str[1:price_range_str.index("-")-1].replace(".",""))
        price_higher = int(price_range_str[price_range_str.index("-")+3:].replace(".",""))
        return price_lower,price_higher
    except:
        return -1,-1

In [19]:
def extract_coordinates(coordinates_str):
    try:
        coordinates = coordinates_str.split(",")
        longitude = float(coordinates[0])
        latitude = float(coordinates[1])
        return longitude,latitude
    except:
        return -1.0,-1.0

In [20]:
def extract_rating(rating_str):
    try:
        rating = float(rating_str[rating_str.index(",")-1:rating_str.index(",")+1].replace(",","."))
        return rating
    except:
        return -1.0

In [21]:
df = pd.read_csv(directory_path + "/" + csv_name)
df.head()

,Column1,link,name,rating,coordinates,city,price,cousine,mealType,priceType,diets,purpose
0,0,https://www.tripadvisor.com.tr/Restaurant_Revi...,Solsiden Restaurant& Sports Bar,"5 baloncuk üzerinden 4,0","36.537334,32.03629",Antalya,₺198 - ₺693,"Bar, Avrupa, İskandinav",NaN,NaN,NaN,NaN
1,1,https://www.tripadvisor.com.tr/Restaurant_Revi...,Le Chevy Restaurant,"5 baloncuk üzerinden 5,0","36.54376,31.989422",Antalya,₺100 - ₺500,"Fransız, Alman, Türk, Rus, Doğu Avrupa, Bar, S...",NaN,NaN,NaN,NaN
2,2,https://www.tripadvisor.com.tr/Restaurant_Revi...,Chefmetin Moonlightrestaurant & Steak House,"5 baloncuk üzerinden 5,0","36.543453,31.996155",Antalya,₺165 - ₺759,"Biftek Restoranı, Uluslararası, Türk",NaN,NaN,NaN,NaN
3,3,https://www.tripadvisor.com.tr/Restaurant_Revi...,Taksim Tünel,"5 baloncuk üzerinden 5,0","36.543354,31.996046",Antalya,NaN,"Uluslararası, Türk, Bar, Avrupa, Sağlıklı, Bar",NaN,NaN,NaN,NaN
4,4,https://www.tripadvisor.com.tr/Restaurant_Revi...,Cozy Alanya,"5 baloncuk üzerinden 5,0","36.536846,31.99173",Antalya,₺100 - ₺1.500,"Akdeniz, Biftek Restoranı, Bar, Pizza",NaN,NaN,NaN,NaN

In [22]:
df = df.drop("Column1", axis=1 )
df = df.rename(columns={'cousine': 'cuisine'})
df = df.rename(columns={'mealType': 'meal_type'})
df = df.rename(columns={'priceType': 'price_type'})
df = df.rename(columns={'priceType': 'price_type'})

df['cuisine'] = df['cuisine'].astype(str).fillna('') + ", " + df['diets'].fillna('')
df = df.drop("diets", axis=1 )
df.head()

,link,name,rating,coordinates,city,price,cuisine,meal_type,price_type,purpose
0,https://www.tripadvisor.com.tr/Restaurant_Revi...,Solsiden Restaurant& Sports Bar,"5 baloncuk üzerinden 4,0","36.537334,32.03629",Antalya,₺198 - ₺693,"Bar, Avrupa, İskandinav,",NaN,NaN,NaN
1,https://www.tripadvisor.com.tr/Restaurant_Revi...,Le Chevy Restaurant,"5 baloncuk üzerinden 5,0","36.54376,31.989422",Antalya,₺100 - ₺500,"Fransız, Alman, Türk, Rus, Doğu Avrupa, Bar, S...",NaN,NaN,NaN
2,https://www.tripadvisor.com.tr/Restaurant_Revi...,Chefmetin Moonlightrestaurant & Steak House,"5 baloncuk üzerinden 5,0","36.543453,31.996155",Antalya,₺165 - ₺759,"Biftek Restoranı, Uluslararası, Türk,",NaN,NaN,NaN
3,https://www.tripadvisor.com.tr/Restaurant_Revi...,Taksim Tünel,"5 baloncuk üzerinden 5,0","36.543354,31.996046",Antalya,NaN,"Uluslararası, Türk, Bar, Avrupa, Sağlıklı, Bar,",NaN,NaN,NaN
4,https://www.tripadvisor.com.tr/Restaurant_Revi...,Cozy Alanya,"5 baloncuk üzerinden 5,0","36.536846,31.99173",Antalya,₺100 - ₺1.500,"Akdeniz, Biftek Restoranı, Bar, Pizza,",NaN,NaN,NaN

In [23]:
df['price_lower'], df['price_higher'] = zip(*df['price'].apply(extract_prices))
df.head()

,link,name,rating,coordinates,city,price,cuisine,meal_type,price_type,purpose,price_lower,price_higher
0,https://www.tripadvisor.com.tr/Restaurant_Revi...,Solsiden Restaurant& Sports Bar,"5 baloncuk üzerinden 4,0","36.537334,32.03629",Antalya,₺198 - ₺693,"Bar, Avrupa, İskandinav,",NaN,NaN,NaN,198,693
1,https://www.tripadvisor.com.tr/Restaurant_Revi...,Le Chevy Restaurant,"5 baloncuk üzerinden 5,0","36.54376,31.989422",Antalya,₺100 - ₺500,"Fransız, Alman, Türk, Rus, Doğu Avrupa, Bar, S...",NaN,NaN,NaN,100,500
2,https://www.tripadvisor.com.tr/Restaurant_Revi...,Chefmetin Moonlightrestaurant & Steak House,"5 baloncuk üzerinden 5,0","36.543453,31.996155",Antalya,₺165 - ₺759,"Biftek Restoranı, Uluslararası, Türk,",NaN,NaN,NaN,165,759
3,https://www.tripadvisor.com.tr/Restaurant_Revi...,Taksim Tünel,"5 baloncuk üzerinden 5,0","36.543354,31.996046",Antalya,NaN,"Uluslararası, Türk, Bar, Avrupa, Sağlıklı, Bar,",NaN,NaN,NaN,-1,-1
4,https://www.tripadvisor.com.tr/Restaurant_Revi...,Cozy Alanya,"5 baloncuk üzerinden 5,0","36.536846,31.99173",Antalya,₺100 - ₺1.500,"Akdeniz, Biftek Restoranı, Bar, Pizza,",NaN,NaN,NaN,100,1500

In [24]:
df['longitude'], df['latitude'] = zip(*df['coordinates'].apply(extract_coordinates))
df.head()

,link,name,rating,coordinates,city,price,cuisine,meal_type,price_type,purpose,price_lower,price_higher,longitude,latitude
0,https://www.tripadvisor.com.tr/Restaurant_Revi...,Solsiden Restaurant& Sports Bar,"5 baloncuk üzerinden 4,0","36.537334,32.03629",Antalya,₺198 - ₺693,"Bar, Avrupa, İskandinav,",NaN,NaN,NaN,198,693,36.537334,32.036290
1,https://www.tripadvisor.com.tr/Restaurant_Revi...,Le Chevy Restaurant,"5 baloncuk üzerinden 5,0","36.54376,31.989422",Antalya,₺100 - ₺500,"Fransız, Alman, Türk, Rus, Doğu Avrupa, Bar, S...",NaN,NaN,NaN,100,500,36.543760,31.989422
2,https://www.tripadvisor.com.tr/Restaurant_Revi...,Chefmetin Moonlightrestaurant & Steak House,"5 baloncuk üzerinden 5,0","36.543453,31.996155",Antalya,₺165 - ₺759,"Biftek Restoranı, Uluslararası, Türk,",NaN,NaN,NaN,165,759,36.543453,31.996155
3,https://www.tripadvisor.com.tr/Restaurant_Revi...,Taksim Tünel,"5 baloncuk üzerinden 5,0","36.543354,31.996046",Antalya,NaN,"Uluslararası, Türk, Bar, Avrupa, Sağlıklı, Bar,",NaN,NaN,NaN,-1,-1,36.543354,31.996046
4,https://www.tripadvisor.com.tr/Restaurant_Revi...,Cozy Alanya,"5 baloncuk üzerinden 5,0","36.536846,31.99173",Antalya,₺100 - ₺1.500,"Akdeniz, Biftek Restoranı, Bar, Pizza,",NaN,NaN,NaN,100,1500,36.536846,31.991730

In [25]:
df['rating'] = df['rating'].apply(extract_rating)
df.head()

,link,name,rating,coordinates,city,price,cuisine,meal_type,price_type,purpose,price_lower,price_higher,longitude,latitude
0,https://www.tripadvisor.com.tr/Restaurant_Revi...,Solsiden Restaurant& Sports Bar,4.0,"36.537334,32.03629",Antalya,₺198 - ₺693,"Bar, Avrupa, İskandinav,",NaN,NaN,NaN,198,693,36.537334,32.036290
1,https://www.tripadvisor.com.tr/Restaurant_Revi...,Le Chevy Restaurant,5.0,"36.54376,31.989422",Antalya,₺100 - ₺500,"Fransız, Alman, Türk, Rus, Doğu Avrupa, Bar, S...",NaN,NaN,NaN,100,500,36.543760,31.989422
2,https://www.tripadvisor.com.tr/Restaurant_Revi...,Chefmetin Moonlightrestaurant & Steak House,5.0,"36.543453,31.996155",Antalya,₺165 - ₺759,"Biftek Restoranı, Uluslararası, Türk,",NaN,NaN,NaN,165,759,36.543453,31.996155
3,https://www.tripadvisor.com.tr/Restaurant_Revi...,Taksim Tünel,5.0,"36.543354,31.996046",Antalya,NaN,"Uluslararası, Türk, Bar, Avrupa, Sağlıklı, Bar,",NaN,NaN,NaN,-1,-1,36.543354,31.996046
4,https://www.tripadvisor.com.tr/Restaurant_Revi...,Cozy Alanya,5.0,"36.536846,31.99173",Antalya,₺100 - ₺1.500,"Akdeniz, Biftek Restoranı, Bar, Pizza,",NaN,NaN,NaN,100,1500,36.536846,31.991730

In [26]:
df = df.drop('price', axis=1)
df = df.rename(columns={'cousine': 'cuisine'})
df = df[desired_order]
df.head()

,city,link,name,rating,price_lower,price_higher,price_type,longitude,latitude,cuisine,meal_type,purpose
0,Antalya,https://www.tripadvisor.com.tr/Restaurant_Revi...,Solsiden Restaurant& Sports Bar,4.0,198,693,NaN,36.537334,32.036290,"Bar, Avrupa, İskandinav,",NaN,NaN
1,Antalya,https://www.tripadvisor.com.tr/Restaurant_Revi...,Le Chevy Restaurant,5.0,100,500,NaN,36.543760,31.989422,"Fransız, Alman, Türk, Rus, Doğu Avrupa, Bar, S...",NaN,NaN
2,Antalya,https://www.tripadvisor.com.tr/Restaurant_Revi...,Chefmetin Moonlightrestaurant & Steak House,5.0,165,759,NaN,36.543453,31.996155,"Biftek Restoranı, Uluslararası, Türk,",NaN,NaN
3,Antalya,https://www.tripadvisor.com.tr/Restaurant_Revi...,Taksim Tünel,5.0,-1,-1,NaN,36.543354,31.996046,"Uluslararası, Türk, Bar, Avrupa, Sağlıklı, Bar,",NaN,NaN
4,Antalya,https://www.tripadvisor.com.tr/Restaurant_Revi...,Cozy Alanya,5.0,100,1500,NaN,36.536846,31.991730,"Akdeniz, Biftek Restoranı, Bar, Pizza,",NaN,NaN

In [27]:
df['price_type'] = df['price_type'].fillna('')
df['meal_type'] = df['meal_type'].fillna('')
df['purpose'] = df['purpose'].fillna('')

In [28]:
df.to_csv(target_path + "/" + csv_name[:csv_name.index('.')] + "_for_db.csv", index=False ,encoding='utf-8-sig')

In [29]:
df.head()

,city,link,name,rating,price_lower,price_higher,price_type,longitude,latitude,cuisine,meal_type,purpose
0,Antalya,https://www.tripadvisor.com.tr/Restaurant_Revi...,Solsiden Restaurant& Sports Bar,4.0,198,693,,36.537334,32.036290,"Bar, Avrupa, İskandinav,",,
1,Antalya,https://www.tripadvisor.com.tr/Restaurant_Revi...,Le Chevy Restaurant,5.0,100,500,,36.543760,31.989422,"Fransız, Alman, Türk, Rus, Doğu Avrupa, Bar, S...",,
2,Antalya,https://www.tripadvisor.com.tr/Restaurant_Revi...,Chefmetin Moonlightrestaurant & Steak House,5.0,165,759,,36.543453,31.996155,"Biftek Restoranı, Uluslararası, Türk,",,
3,Antalya,https://www.tripadvisor.com.tr/Restaurant_Revi...,Taksim Tünel,5.0,-1,-1,,36.543354,31.996046,"Uluslararası, Türk, Bar, Avrupa, Sağlıklı, Bar,",,
4,Antalya,https://www.tripadvisor.com.tr/Restaurant_Revi...,Cozy Alanya,5.0,100,1500,,36.536846,31.991730,"Akdeniz, Biftek Restoranı, Bar, Pizza,",,